[package]
name = "icaros"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.4"
ratatui = "0.26"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
notify = "6.1"
dirs = "5.0"

[dev-dependencies]
tempfile = "3.8"
