name: Manual Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump version
        id: bump
        run: |
          # Use the bump-version script with the specified type
          ./.github/scripts/bump-version.sh ${{ inputs.bump_type }}
          
          # Get the new version
          NEW_VERSION=$(grep '^version = ' Cargo.toml | head -1 | cut -d'"' -f2)
          
          # Update Cargo.lock
          cargo update --package icaros
          
          # Commit changes
          git add Cargo.toml Cargo.lock
          git commit -m "chore: bump version to $NEW_VERSION"
          
          # Create and push tag
          NEW_TAG="v$NEW_VERSION"
          git tag "$NEW_TAG"
          git push origin main --tags
          
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Released version $NEW_VERSION with tag $NEW_TAG"

      - name: Trigger release workflow
        run: |
          echo "Version bumped to ${{ steps.bump.outputs.new_tag }}"
          echo "The release workflow will be triggered automatically by the new tag."